FROM python:3.13-slim AS base

WORKDIR /app

# no pycache or bycode imports
ENV PYTHONDONTWRITEBYTECODE 1
# unbuffered stdout and stderr
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y build-essential libpq-dev
COPY fishscalebackend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .

FROM base AS final
EXPOSE 8000

# running locally for development.
CMD ["gunicorn", "fishscalebackend.wsgi:application", "--bind", "0.0.0.0:8000"]